In [1]:
import numpy as np

def bubble_sort(A):
    swap = True
    
    while swap:
        swap = False
        for i in range(len(A)-1):
            
            if A[i+1] < A[i]:
                A[i], A[i+1] = A[i+1], A[i]
                swap = True
    return A  

In [5]:
for i in range(5):
    rnd = np.random.randint(1,50,14)
    unsorted = rnd.copy()
    u2 = unsorted.copy()
    rnd.sort()
    
    sorted_array = bubble_sort(unsorted)
    assert rnd.all() == sorted_array.all()
    print (u2, sorted_array)

[16 41  4 23 34 43  5 14 10 17 15 16 49 39] [ 4  5 10 14 15 16 16 17 23 34 39 41 43 49]
[15 42 21 48 14 37  8 14 42 22 40 25  9 10] [ 8  9 10 14 14 15 21 22 25 37 40 42 42 48]
[34 29  3  6 33 38  5 25  2 46 36 38  6 21] [ 2  3  5  6  6 21 25 29 33 34 36 38 38 46]
[31 49 32 47 36 34  2 20 26 46  6  3 17 31] [ 2  3  6 17 20 26 31 31 32 34 36 46 47 49]
[41  3 12 40 36 29 16  5 31 39 45 35 18 43] [ 3  5 12 16 18 29 31 35 36 39 40 41 43 45]


In [10]:
print bubble_sort(unsorted)

[ 2  5 16 17 30 30 32 32 32 40 43 44 45 49]
