In [13]:
import numpy as np

def mergesort(alist):
    buffer = [None] * len(alist)
    return mergesort_helper(alist, buffer, 0, len(alist)-1 )
    
    
def mergesort_helper(alist, buffer, low, high):
    
    if low < high:
        middle = (low + high) // 2
        mergesort_helper(alist, buffer, low, middle)
        mergesort_helper(alist, buffer, middle+1, high)
        merge(alist, buffer, low, middle, high)
    return alist

def merge(alist, buffer, low, middle, high):
    for i in range(low, high + 1):
        buffer[i] = alist[i]
    
    buffer_left = low
    buffer_right = middle+1
    current = low
    
    while buffer_left <= middle and buffer_right <= high:
        if buffer[buffer_left] <= buffer[buffer_right]:
            alist[current] = buffer[buffer_left]
            buffer_left += 1
        else:
            alist[current] = buffer[buffer_right]
            buffer_right += 1
        current += 1
        
        #copy rest of the lest side of the arra to the target array
        
        remaining = middle - buffer_left
        for i in range(0, remaining+1):
            alist[current + i] = buffer[buffer_left+i]

In [14]:
for i in range(5):
    rnd = np.random.randint(1,50,7)
    unsorted = rnd.copy()
    rnd.sort()
    print (unsorted)
    print(mergesort(unsorted))
    assert rnd.all() == mergesort(unsorted).all()
    

[32  2  6 20  4 30 49]
[ 2  4  6 20 30 32 49]
[23 16 10 33 25 13 19]
[10 13 16 19 23 25 33]
[39  1 22 22 40 39 47]
[ 1 22 22 39 39 40 47]
[33 42 36 14  6  3 15]
[ 3  6 14 15 33 36 42]
[36 26 49  4 31 19 48]
[ 4 19 26 31 36 48 49]
