In [55]:
import numpy as np

def quicksort(alist):
    return quicksort_helper(alist, 0, len(alist)-1)

def quicksort_helper(alist, left, right):
    #print("list: {}, left: {}, right: {}".format(alist, left, right))
    idx = partition(alist, left, right)
    
    if left < idx-1:
        quicksort_helper(alist, left, idx-1)
    if idx < right:
        quicksort_helper(alist, idx, right)
    return alist
    

def partition(alist, left, right):
    pivot = alist[(left+right)//2]
    
    while left <= right:
        while alist[left] < pivot:
            left += 1
            
        while alist[right] > pivot:
            right -= 1
        if left <= right:
            alist[left], alist[right] = alist[right], alist[left]
            left += 1
            right -= 1
    return left
    

In [56]:
for i in range(5):
    rnd = np.random.randint(1,50,7)
    unsorted = rnd.copy()
    rnd.sort()
    print (unsorted)
    print(quicksort(unsorted))
    assert rnd.all() == quicksort(unsorted).all()
    
    

[48 20 36 44 35 49 15]
[15 20 35 36 44 48 49]
[24 17 44 11 27 26  4]
[ 4 11 17 24 26 27 44]
[16 26  6  7 48 26 10]
[ 6  7 10 16 26 26 48]
[25 48 42 28 18  4 35]
[ 4 18 25 28 35 42 48]
[49  9 33 46  2 34 22]
[ 2  9 22 33 34 46 49]
