In [58]:
import numpy as np

def selection_sort(alist):

    for i in range(len(alist)):
        min_idx = i
        
        for j in range(i+1, len(alist)):
            if alist[j] < alist[min_idx]:
                min_idx = j
        alist[i], alist[min_idx] =  alist[min_idx], alist[i]
    return alist
    

In [59]:
for i in range(5):
    rnd = np.random.randint(1,50,14)
    unsorted = rnd.copy()
    rnd.sort()
    print unsorted
    assert rnd.all() == selection_sort(unsorted).all()
    

[46 14 48  9 19 46 17 48  6 33 27 39 19  3]
[31 30 22 29 26 28 40  7 16 15 16 17 39 15]
[18 47  7 14 45 31  4 44 30 47 25 46  3 22]
[22 42 33 13 20 46  3  1 28 37 49  8 40 34]
[ 1 10 49 21 18 17 15 39  2 32 27 32 28 34]


In [65]:
rnd = np.random.randint(1,20,8)
selection_sort(rnd)

array([ 1,  6,  9, 13, 13, 16, 16, 18])

In [31]:
%timeit selection_sort(rnd)

The slowest run took 5.50 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.37 µs per loop


array([8, 6, 6, 5])